# Generated by Django 5.0.1 on 2025-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circlename', models.CharField(max_length=100)),
                ('regionname', models.CharField(max_length=100)),
                ('divisionname', models.CharField(max_length=100)),
                ('officename', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('officetype', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('statename', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
