# Generated by Django 5.0.1 on 2025-03-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
