# Generated by Django 5.1.6 on 2025-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_postoffice_latitude_alter_postoffice_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_image', models.ImageField(upload_to='scanned_mails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
